######################################################################
# Automatically generated by qmake (2.01a) ? 1 23 22:26:42 2012
######################################################################

TEMPLATE = vcapp
TARGET = HelloQtWorld
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS       = mainwindow.h
SOURCES       = main.cpp mainwindow.cpp
RESOURCES     = application.qrc
